-- depends: tokens teams standings scores rounds results players notification_logs logs fixtures current_round choices call_logs

-- CALL_LOGS
TRUNCATE TABLE CALL_LOGS;
INSERT INTO CALL_LOGS SELECT * FROM FPG.CALL_LOGS;

-- CHOICES
TRUNCATE TABLE CHOICES;
INSERT INTO CHOICES SELECT * FROM FPG.CHOICES;

-- CURRENT_ROUND 
TRUNCATE TABLE CURRENT_ROUND;
INSERT INTO CURRENT_ROUND SELECT * FROM FPG.CURRENT_ROUND;

-- FIXTURES
TRUNCATE TABLE FIXTURES;
INSERT INTO FIXTURES SELECT * FROM FPG.FIXTURES;

-- LOGS
TRUNCATE TABLE LOGS;
INSERT INTO LOGS SELECT * FROM FPG.LOGS;

-- NOTIFICATION_LOGS
-- TRUNCATE TABLE NOTIFICATION_LOGS;
-- INSERT INTO NOTIFICATION_LOGS SELECT * FROM FPG.NOTIFICATION_LOGS;

-- PLAYERS
TRUNCATE TABLE PLAYERS;
INSERT INTO PLAYERS SELECT * FROM FPG.PLAYERS;

-- RESULTS
TRUNCATE TABLE RESULTS;
INSERT INTO RESULTS SELECT * FROM FPG.RESULTS;

-- ROUNDS
TRUNCATE TABLE ROUNDS;
INSERT INTO ROUNDS SELECT * FROM FPG.ROUNDS;

-- SCORES
TRUNCATE TABLE SCORES;
INSERT INTO SCORES SELECT * FROM FPG.SCORES;

-- STANDINGS
TRUNCATE TABLE STANDINGS;
INSERT INTO STANDINGS SELECT * FROM FPG.STANDINGS;

-- TEAMS
TRUNCATE TABLE TEAMS;
INSERT INTO TEAMS SELECT * FROM FPG.TEAMS;

-- TOKENS
-- TRUNCATE TABLE TOKENS;
-- INSERT INTO TOKENS SELECT * FROM FPG.TOKENS;
