CREATE TABLE IF NOT EXISTS YOYO_TEST_SECOND (
    COL1 VARCHAR(255) NOT NULL,
    COL2 VARCHAR(255) NOT NULL,
    COL3 VARCHAR(255) NOT NULL,
    COL4 VARCHAR(255) NOT NULL, 
    COL5 VARCHAR(255) NOT NULL
);