name: Deploy to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest

    environment: development

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: yoyo-deploy
        uses: ./.github/actions/yoyo_deploy
        with:
          database: ${{ vars.DATABASE }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
